export const test = [
    {
        'id': 0,
        'name': 'test',
        'mana': 0,
        'cost': 0,
        'HP': 0,
        'desc': "Test",
        'attack' : 0,
        'effect': 'Aucun',
        'type': ['Aucun'],
        'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBqUERnQhQfeIHt7q_AR9JuG1kkQHwcCV1lA&usqp=CAU'
    },
    {
        'id': 1,
        'name': 'qsdqsdqsdqsd',
        'mana': 1,
        'cost': 1,
        'attack' : 2,
        'HP': 1,
        'desc': "Teqsdqsdqs2",
        'effect': 'Aucun',
        'type': ['Aucun'],
        'image': '../images/img2.jpg'
    },
    {
        'id': 2,
        'name': 'Tqsdqsd',
        'mana': 3,
        'cost': 3,
        'HP': 3,
        'attack' : 3,
        'desc': "Tqsdqd3",
        'effect': 'Aucun',
        'type': ['Aucun'],
        'image': '../images/img3.jpg'
    },
    {
        'id': 3,
        'name': 'Un nom',
        'mana': 0,
        'cost': 0,
        'attack' : 0,
        'HP': 0,
        'desc': "Test",
        'effect': 'Aucun',
        'type': ['Aucun'],
        'image': '../images/img4.jpg'
    },
    {
        'id': 4,
        'name': 'Un autre nom !',
        'mana': 0,
        'cost': 1,
        'attack' : 2,
        'HP': 1,
        'desc': "Test",
        'effect': 'Aucun',
        'type': ['Aucun'],
        'image': '../images/img5.jpg'
    },
    {
        'id': 5,
        'name': 'Yaru',
        'mana': 0,
        'cost': 0,
        'HP': 0,
        'attack' : 0,
        'desc': "Test",
        'effect': 'Aucun',
        'type': ['Aucun'],
        'image': '../images/img6.jpg'
    },
    {
        'id': 6,
        'name': 'qsmlkdsq',
        'mana': 0,
        'cost': 0,
        'HP': 0,
        'attack' : 0,
        'desc': "Test",
        'effect': 'Aucun',
        'type': ['Aucun'],
        'image': '../images/img7.jpg'
    },
    {
        'id': 7,
        'name': 'skjdlqskjd',
        'mana': 0,
        'cost': 0,
        'attack' : 0,
        'HP': 0,
        'desc': "Test",
        'effect': 'Aucun',
        'type': ['Aucun'],
        'image': '../images/img8.jpg'
    }];